name: Release Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.13'

      - name: Build Book
        run: mdbook build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: book/
          enable_jekyll: true
          publish_branch: pages
          force_orphan: true
